### ISSUE TITLE
CredEnum Exception

### ISSUE THREAD

**Issue by leechristensen** [GhostPack/Seatbelt#71]
**Describe the bug**
When running the CredEnum command, it failed with the following exception:

```
ERROR:   [!] Terminating exception running command 'CredEnum': System.ComponentModel.Win32Exception (0x80004005): Element not found
   at Windows.CredEnumCommand.<Execute>d__9.MoveNext()
   at Runtime.ExecuteCommand(CommandBase command, String[] commandArgs)
```
It looks like it may be accessing an array incorrectly?

**To Reproduce**
I don't have access to a system where I can reproduce this .  Occurred when running the `CredEnum` command

**Expected behavior**
The module to run and dump creds, or not print anything (or a message saying there weren't any)

**Observed behavior**
An exception was thrown

**Comment by leechristensen** [comment]
For the "Element not found" exception, I can reproduce it when I'm logged in as a user and then run "runas /user:blah cmd.exe" and then run Seatbelt in the new command prompt.

**Comment by UP942901** [comment]
Happening to me too.
