### ISSUE TITLE
WMI Error in the InterestingProcesses Command

### ISSUE THREAD

**Issue by leechristensen** [GhostPack/Seatbelt#74]
**Describe the bug**
An exception is being thrown during the InterestingProcesses command:
```
ERROR:   [!] Terminating exception running command 'InterestingProcesses': System.Management.ManagementException: Not found 
   at System.Management.ManagementException.ThrowWithExtendedInfo(ManagementStatus errorCode)
   at System.Management.ManagementObject.InvokeMethod(String methodName, ManagementBaseObject inParameters, InvokeMethodOptions options)
   at System.Management.ManagementObject.InvokeMethod(String methodName, Object[] args)
   at Seatbelt.Commands.Windows.InterestingProcessesCommand.<Execute>d__10.MoveNext()
   at Seatbelt.Runtime.ExecuteCommand(CommandBase command, String[] commandArgs)
```

I don't have access to a host where it occurs.
Looks like it may manifest itself on 2012 R2 machines. Might also occur after performing lateral movement to a host using WMI or WinRM.

Looks like it might be caused when obtaining the process owner (that's the only place a WMI method is invoked)

**To Reproduce**
Run Seatbelt's InterestingProcesses command.

**Expected behavior**
The command to run, displaying interesting process, or a notification saying that there aren't any or it's not possible to run this command.

**Observed behavior**
Some processes are output, but then the process listing is cut short due to an exception

**Comment by leechristensen** [comment]
Should be addressed in #78
