### ISSUE TITLE
PSSessionSettings null value exception

### ISSUE THREAD

**Issue by leechristensen** [GhostPack/Seatbelt#77]
**Describe the bug**
When running the PSSessionSettings command, it failed with the following exception:

```
====== PSSessionSettings ======

  Name : Microsoft.PowerShell
    BUILTIN\Administrators                 AccessAllowed      

ERROR:   [!] Terminating exception running command 'PSSessionSettings': System.ArgumentNullException: Value cannot be null.
Parameter name: s
   at System.IO.StringReader..ctor(String s)
   at System.Xml.XmlDocument.LoadXml(String xml)
   at Windows.PSSessionSettingsCommand.<Execute>d__10.MoveNext()
   at Runtime.ExecuteCommand(CommandBase command, String[] commandArgs)
```

**To Reproduce**
I don't have access to a system where I can reproduce the first error .  Occurred when running the `PSSessionSettings` command on a Windows 7 Enterprise system.

**Expected behavior**
The module to run and display this PS session settings or not display anything at all

**Observed behavior**
An exception was thrown

**Comment by leechristensen** [comment]
Should be addressed in #78
